language: node_js
node_js:
    - stable

env:
    global:
        - DISPLAY=":99.0"

matrix:
    include:
        - env: FF_REQUIRED="38.0a1"
          addons:
              firefox: "38.0a1"
              apt:
                  packages:
                      - ca-certificates
                      - sharutils
                      - poppler-utils
        - env: FF_REQUIRED="45.0"
          addons:
              firefox: "45.0"
              apt:
                  packages:
                      - ca-certificates
                      - sharutils
                      - poppler-utils
        - env: FF_REQUIRED="52.0"
          addons:
              firefox: "52.0"
              apt:
                  packages:
                      - ca-certificates
                      - sharutils
                      - poppler-utils
        - env: FF_REQUIRED="latest"
          addons:
              firefox: "latest"
              apt:
                  packages:
                      - ca-certificates
                      - sharutils
                      - poppler-utils

before_install:
    - sh -e /etc/init.d/xvfb start
    - npm install -g jpm

before_script:
    - export FFBIN="$(which firefox)"
    - jpm --version
    - which pdftotext && which firefox && firefox -version && which firefox-bin && firefox-bin -version

script:
    - jpm xpi -v --addon-dir src/ --dest-dir . && unzip -l cmdlnprint.xpi
    - jpm run -v --addon-dir src/ --binary "${FFBIN}" --binary-args '-print src/test/assets/sample.html -print-mode pdf -print-file /tmp/output.pdf'
    - pdftotext -raw /tmp/output.pdf /tmp/output.txt && diff -q src/test/assets/expected-output.txt /tmp/output.txt
    - cat /tmp/output.txt
    - cat /tmp/output.pdf | uuencode output.pdf
