language: node_js
node_js:
    - stable

env:
    global:
        - DISPLAY=:99.0

addons:
    firefox: "45.0"
    apt:
        packages:
            - ca-certificates
            - sharutils

before_install:
    - sh -e /etc/init.d/xvfb start
    - npm install -g jpm

before_script:
    - jpm --version
    - export FFBIN="$(which firefox)"
    - which firefox && firefox -version && which firefox-bin && firefox-bin -version

script:
    - jpm xpi -v --addon-dir src/ --dest-dir . && unzip -l cmdlnprint.xpi
    - jpm run -v --addon-dir src/ --binary "${FFBIN}" --binary-args '-print src/test/assets/sample.html -print-mode pdf -print-file /tmp/test.pdf'
    - cat /tmp/test.pdf | uuencode test.pdf
