language: node_js
node_js:
    - stable

env:
    global:
        - DISPLAY=:99.0

addons:
    apt:
        packages:
            - ca-certificates
            - sharutils

before_install:
    - sh -e /etc/init.d/xvfb start
    - npm install -g jpm

before_script:
    - jpm --version
    - export FFBIN="$(which firefox)"
    - which firefox && firefox -version

script:
    - cd $TRAVIS_BUILD_DIR/src
    - jpm xpi -v && unzip -l cmdlnprint.xpi
    - jpm run -v --binary "${FFBIN}" --binary-args '-print tests/assets/sample.html -print-mode pdf -print-file /tmp/test.pdf'
    - cat /tmp/test.pdf | uuencode test.pdf
